#!/bin/python
from argparse import ArgumentParser
from os.path import commonprefix
import h5py

parser = ArgumentParser()
parser.add_argument("fnames", nargs="+", help="files that should be averaged")
args = parser.parse_args()


def main():
    fnames = args.fnames
    file, data = average(fnames)

    prefix = commonprefix(["_".join(fname.split("_")[:-1]) for fname in fnames])
    output = h5py.File(prefix + "_average.hdf", "w")
    copy_structure(file, output, ["CellData", "FieldData"])

    output.create_group("/VTKHDF/CellData")
    for key, dset in data.items():
        output["/VTKHDF/CellData"].create_dataset(key, data=dset)


def average(fnames):
    file = h5py.File(fnames[0], "r")
    keys = file["/VTKHDF/CellData"].keys()

    data = {}
    for key in keys:
        data[key] = file[f"/VTKHDF/CellData/{key}"][...]

    for fname in fnames[1:]:
        file = h5py.File(fname)
        for key in keys:
            data[key] += file[f"/VTKHDF/CellData/{key}"]

    for key in keys:
        data[key] = (data[key] / len(fnames)).astype(data[key].dtype)

    return file, data


def copy_structure(source, dest, filter=None):
    for key, item in source.items():
        if isinstance(item, h5py.Group):
            if filter and key in filter:
                pass
            else:
                group = dest.create_group(key)
                copy_attributes(item, group)
                copy_structure(item, group, filter)
        else:
            dset = dest.create_dataset(key, data=item)
            copy_attributes(item, dset)


def copy_attributes(source, dest):
    for key, item in source.attrs.items():
        dest.attrs[key] = item


if __name__ == "__main__":
    main()
