#!/bin/bash

ntasks=1
while getopts "n:" opt; do
    case $opt in
        n) ntasks=$OPTARG ;;
        *) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

prog=$1
args=${@:2}

if [ $ntasks -gt 1 ]; then
    exec mpirun -n $ntasks xterm -e gdb -q -ex run --args $prog $args
else
    exec gdb -q -ex run --args $prog $args
fi
