#!/bin/bash

num_cores=1
while getopts "n:" opt; do
    case $opt in
        n) num_cores=$OPTARG ;;
        *) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

prog=$1
args=${@:2}

if [ $num_cores -gt 1 ]; then
    exec mpirun -n 1 lldb -o 'b main' -o 'run' -- $prog $args : -n $((num_cores - 1)) $prog $args
else
    exec lldb -o 'b main' -o 'run' -- $prog $args
fi
