#!/bin/bash

ntasks=1
while getopts "n:" opt; do
    case $opt in
        n) ntasks=$OPTARG ;;
        *) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

prog=$1
args=${@:2}

if [ $ntasks -gt 1 ]; then
    exec mpirun -n 1 lldb -o 'b main' -o 'run' -- $prog $args : -n $((ntasks - 1)) $prog $args
else
    exec lldb -o 'b main' -o 'run' -- $prog $args
fi
