#!/bin/bash

ntasks=1
while getopts "n:" opt; do
    case $opt in
        n) ntasks=$OPTARG ;;
        *) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

prog=$1
args=${@:2}

exec mpirun -n $ntasks valgrind -q --tool=memcheck --gen-suppressions=no \
    --suppressions=tools/openmpi.supp --suppressions=tools/thread.supp \
    --leak-check=full --track-origins=yes \
    $prog $args
