#!/usr/bin/env bash

ntasks=1
frequency=200
while getopts "n:f:" opt; do
    case $opt in
        n) ntasks=$OPTARG ;;
        f) frequency=$OPTARG ;;
        *) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

prog=$1

dat=${prog}_perf.dat
out=${prog}_perf.out
pdf=${prog}_perf.pdf

perf record -F $frequency -g -o $dat -- mpirun -n $ntasks "$@"
perf report -i $dat --stdio > $out
perf script -i $dat | gprof2dot -f perf | dot -Tpdf -o $pdf
