#!/usr/bin/env python3

import os
from argparse import ArgumentParser
from pathlib import Path

import imageio.v2 as imageio
import numpy as np
from PyPDF2 import PdfMerger
import pyvista as pv
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpi4py import MPI


def parse_args():
    parser = ArgumentParser(description="Visualize an unstructured grid")
    parser.add_argument("fnames", nargs="+", help="input file(s)")
    parser.add_argument("-f", "--field", help="field to plot")
    parser.add_argument("-l", "--list", action="store_true", help="list all plottable fields")
    parser.add_argument("--points", action="store_true", help="interpolate to points")
    parser.add_argument("--explode", action="store_true", help="explode cells")
    parser.add_argument("--edges", action="store_true", help="show edges")
    parser.add_argument("--clip", action="store_true", help="add clip plane")
    parser.add_argument("--crinkle", action="store_true", help="crinkle clip")
    parser.add_argument("--line", action="store_true", help="plot over line")
    parser.add_argument("--save", action="store_true", help="save plot instead of showing it")
    parser.add_argument("--video", action="store_true", help="create a video")
    parser.add_argument("--vmin", type=float, help="minimum field value")
    parser.add_argument("--vmax", type=float, help="maximum field value")
    parser.add_argument("--cmap", default="coolwarm", help="colormap")
    return parser.parse_args()


def prepare_mesh(mesh, args):
    if args.field:
        mesh.set_active_scalars(args.field)
    if args.points:
        mesh = mesh.cell_data_to_point_data()
    if args.explode:
        mesh = mesh.explode()
    else:
        vol_types = np.array([10, 12, 13, 14], dtype=np.uint8)
        keep = np.where(np.isin(mesh.celltypes, vol_types))[0]
        mesh = mesh.extract_cells(keep).clean()
    return mesh


def plot_line(mesh, args, fname=None):
    xmin = mesh.points.min(axis=0)[0]
    xmax = mesh.points.max(axis=0)[0]
    mean = mesh.points.mean(axis=0)

    pointa = (xmin, mean[1], mean[2])
    pointb = (xmax, mean[1], mean[2])
    sample = mesh.sample_over_line(pointa, pointb, resolution=1000)

    fig, ax = plt.subplots()

    for name in sample.array_names:
        if args.field not in name:
            continue

        zorder = 1 if "exact" in name else 2
        data = sample[name]

        if data.ndim == 1:
            ax.plot(sample.points[:, 0], data, label=name, zorder=zorder)
        elif data.ndim == 2:
            if data.shape[1] == 3:
                for i, dim in enumerate([" x", " y", " z"]):
                    ax.plot(sample.points[:, 0], data[:, i], label=name + dim, zorder=zorder)
            elif data.shape[1] == 9:
                for i, dim in enumerate(
                    [" xx", " xy", " xz", " yx", " yy", " yz", " zx", " zy", " zz"]
                ):
                    ax.plot(sample.points[:, 0], data[:, i], label=name + dim, zorder=zorder)
        else:
            norm = np.linalg.norm(data, axis=-1)
            ax.plot(sample.points[:, 0], norm, label=name + " norm", zorder=zorder)

    ax.legend()
    ax.set_xlabel("x-axis")
    ax.set_ylabel(args.field)
    ax.set_ylim(args.vmin, args.vmax)

    fig.tight_layout()
    if fname is None:
        plt.show()
    elif args.video:
        fname = Path(fname).with_suffix(".png")
        fig.savefig(fname, dpi=600, bbox_inches="tight")
    else:
        fname = Path(fname).with_suffix(".pdf")
        fig.savefig(fname, dpi=600, bbox_inches="tight")
    plt.close()


def save_screenshot(img, bounds, vmin, vmax, args, fname):
    fig, ax = plt.subplots()

    xmin, xmax, ymin, ymax, _, _ = bounds
    im = ax.imshow(
        img,
        cmap=args.cmap,
        extent=(xmin, xmax, ymin, ymax),
        vmin=vmin,
        vmax=vmax,
        interpolation="none",
    )

    div = make_axes_locatable(ax)
    cax = div.append_axes("right", size=0.15, pad=0.1)
    cb = plt.colorbar(im, cax=cax)
    cb.set_label(args.field)

    ax.set_xlabel("x-axis")
    ax.set_ylabel("y-axis")

    fig.tight_layout()
    if args.video:
        fname = Path(fname).with_suffix(".png")
        fig.savefig(fname, dpi=600, bbox_inches="tight")
    else:
        fname = Path(fname).with_suffix(".pdf")
        fig.savefig(fname, dpi=600, bbox_inches="tight")
    plt.close()


def get_data_range(mesh, args):
    if args.field is None:
        return None, None

    data = mesh[args.field]
    if data.ndim == 1:
        vmin, vmax = data.min(), data.max()
    else:
        norm = np.linalg.norm(data, axis=1)
        vmin, vmax = norm.min(), norm.max()

    if args.vmin is not None:
        vmin = args.vmin
    if args.vmax is not None:
        vmax = args.vmax
    return (vmin, vmax)


def plot_field(mesh, args, fname=None):
    if fname is None:
        plotter = pv.Plotter(lighting="three lights")
    else:
        plotter = pv.Plotter(lighting="three lights", off_screen=True, window_size=[4000, 4000])

    if args.explode:
        plotter.disable_ssao()

    vmin, vmax = get_data_range(mesh, args)
    kwargs = dict(
        show_edges=args.edges,
        clim=(vmin, vmax) if vmin is not None and vmax is not None else None,
        cmap=args.cmap,
        show_scalar_bar=fname is None,
    )
    if args.clip:
        plotter.add_mesh_clip_plane(mesh, crinkle=args.crinkle, **kwargs)
    else:
        plotter.add_mesh(mesh, **kwargs)

    if fname is None:
        plotter.view_xy()
        plotter.show()
    else:
        plotter.camera.tight(view="xy")
        img = plotter.screenshot(None, transparent_background=True, return_img=True)
        plotter.close()
        save_screenshot(img, mesh.bounds, vmin, vmax, args, fname)


def make_video(args):
    prefix = "_".join(args.fnames[0].split("_")[:-1])
    fnames = [str(Path(fname).with_suffix(".png")) for fname in args.fnames]

    frames = []
    for fname in sorted(fnames):
        frame = imageio.imread(fname)
        h, w = frame.shape[:2]
        pad_h = h % 2
        pad_w = w % 2
        if pad_h or pad_w:
            pad = ((0, pad_h), (0, pad_w))
            if frame.ndim == 3:
                pad = pad + ((0, 0),)
            frame = np.pad(frame, pad, mode="edge")
        frames.append(frame)

    imageio.mimsave(f"{prefix}_{args.field}.mp4", frames, fps=20, macro_block_size=1)

    for fname in fnames:
        os.remove(fname)


def make_pdf(args):
    prefix = "_".join(args.fnames[0].split("_")[:-1])
    fnames = [str(Path(fname).with_suffix(".pdf")) for fname in args.fnames]

    merger = PdfMerger()
    for fname in sorted(fnames):
        merger.append(fname)

    with open(f"{prefix}_{args.field}.pdf", "wb") as fh:
        merger.write(fh)
    merger.close()

    for fname in fnames:
        os.remove(fname)


def plot_frames(args):
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()

    for fname in args.fnames[rank::size]:
        mesh = pv.read(fname)
        mesh = prepare_mesh(mesh, args)
        if args.line and args.field:
            plot_line(mesh, args, fname)
        else:
            plot_field(mesh, args, fname)
        print(rank, fname)

    comm.Barrier()
    if rank == 0:
        if args.video:
            make_video(args)
        else:
            make_pdf(args)


def main():
    args = parse_args()
    fnames = args.fnames

    if args.list:
        mesh = pv.read(fnames[0])
        print("\n".join(mesh.array_names))
        return

    save = fnames[0] if args.save else None

    if len(fnames) == 1:
        mesh = pv.read(fnames[0])
        mesh = prepare_mesh(mesh, args)
        if args.line and args.field:
            plot_line(mesh, args, save)
        else:
            plot_field(mesh, args, save)
        return

    if args.field:
        plot_frames(args)


if __name__ == "__main__":
    main()
