#!/bin/bash

ncores=$1 # number of cores
prog=$2 # program
args=${@:3} # program arguments

out=${2}_profile.out
pdf=${2}_profile.pdf

GMON_OUT_PREFIX=gmon.out- mpirun -x GMON_OUT_PREFIX -n $ncores $prog $args
gprof -s $prog gmon.out-*
gprof $prog gmon.sum | tee $out | gprof2dot | dot -Tpdf -o $pdf
rm gmon.out-* gmon.sum
