#!/bin/bash
GMON_OUT_PREFIX=gmon.out- mpirun -x GMON_OUT_PREFIX -n "$@"
gprof -s "$2" gmon.out-*
gprof "$2" gmon.sum | tee "$2_profile.out" | gprof2dot | dot -Tpdf -o "$2_profile.pdf"
rm gmon.out-* gmon.sum
