#!/usr/bin/env python3

from argparse import ArgumentParser
import darkdetect
import pyvista as pv


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("fname")
    parser.add_argument("scalars", nargs="?", default=None)
    parser.add_argument("-l", "--list", action="store_true")
    parser.add_argument("-p", "--points", action="store_true")
    parser.add_argument("-g", "--gradient", nargs=1, default=None)
    parser.add_argument("-d", "--divergence", nargs=1, default=None)
    parser.add_argument("-v", "--vorticity", nargs=1, default=None)
    parser.add_argument("-q", "--qcriterion", nargs=1, default=None)
    parser.add_argument("-x", "--explode", nargs="?", type=float, const=1, default=None)
    parser.add_argument("-t", "--threshold", nargs=3, default=None)
    parser.add_argument("-i", "--isosurfaces", nargs="+", default=None)
    parser.add_argument("-I", "--num_isosurfaces", nargs=2, default=None)
    parser.add_argument("-c", "--clip", nargs="*", type=float, default=None)
    parser.add_argument("-s", "--slice", nargs="*", type=float, default=None)
    parser.add_argument("--theme", default="document" if darkdetect.isLight() else "dark")
    parser.add_argument("--lighting", default="light kit")
    parser.add_argument("--edges", action="store_true")
    parser.add_argument("--cmap", default="RdYlBu_r")
    parser.add_argument("--bounds", action="store_true")
    parser.add_argument("--axes", action="store_true")
    return parser.parse_args()


def compute_field(mesh, scalars):
    quality = [
        "scaled_jacobian",
        "jacobian",
        "radius_ratio",
        "aspect_ratio",
        "max_edge_ratio",
        "skew",
        "condition",
        "volume",
    ]
    if scalars in quality and scalars not in mesh.array_names:
        mesh = mesh.cell_quality(scalars)

    if scalars is not None and scalars not in mesh.array_names:
        supported = sorted(set(mesh.array_names) | set(quality))
        raise ValueError(f"unknown scalars: {scalars} (supported: {supported})")

    return mesh


def apply_args(mesh, args):
    mesh = compute_field(mesh, args.scalars)

    if args.points or args.isosurfaces or args.num_isosurfaces:
        mesh = mesh.cell_data_to_point_data()

    if args.gradient is not None:
        scalars = args.gradient[0]
        mesh = compute_field(mesh, scalars)
        mesh = mesh.compute_derivative(scalars=scalars, gradient="g")

    if args.divergence is not None:
        scalars = args.divergence[0]
        mesh = compute_field(mesh, scalars)
        mesh = mesh.compute_derivative(scalars=scalars, gradient=False, divergence="d")

    if args.vorticity is not None:
        scalars = args.vorticity[0]
        mesh = compute_field(mesh, scalars)
        mesh = mesh.compute_derivative(scalars=scalars, gradient=False, vorticity="v")

    if args.qcriterion is not None:
        scalars = args.qcriterion[0]
        mesh = compute_field(mesh, scalars)
        mesh = mesh.compute_derivative(scalars=scalars, gradient=False, qcriterion="q")

    if args.explode is not None:
        mesh = mesh.explode(factor=args.explode)

    if args.threshold is not None:
        scalars, value = args.threshold[0], tuple(map(float, args.threshold[1:]))
        mesh = compute_field(mesh, scalars)
        mesh = mesh.threshold(scalars=scalars, value=value)

    if args.isosurfaces is not None:
        scalars, isosurfaces = args.isosurfaces[0], tuple(map(float, args.isosurfaces[1:]))
        mesh = compute_field(mesh, scalars)
        mesh = mesh.contour(scalars=scalars, isosurfaces=isosurfaces, compute_normals=True)

    if args.num_isosurfaces is not None:
        scalars, num_isosurfaces = args.num_isosurfaces[0], int(args.num_isosurfaces[1])
        mesh = compute_field(mesh, scalars)
        mesh = mesh.contour(scalars=scalars, isosurfaces=num_isosurfaces, compute_normals=True)

    if args.clip is not None:
        normal = (0, 0, 1) if len(args.clip) == 0 else tuple(args.clip)
        mesh = mesh.clip(normal=normal, crinkle=True)

    if args.slice is not None:
        normal = (0, 0, 1) if len(args.slice) == 0 else tuple(args.slice)
        mesh = mesh.slice(normal=normal)

    return mesh


def main():
    args = parse_args()

    mesh = pv.read(args.fname)
    if args.list:
        for name in mesh.array_names:
            print(name)
        return

    mesh = apply_args(mesh, args)

    pv.set_plot_theme(args.theme)
    plot = pv.Plotter(lighting=args.lighting)

    plot.add_mesh(
        mesh,
        scalars=args.scalars,
        show_edges=args.edges,
        cmap=args.cmap,
        smooth_shading=True if args.isosurfaces is not None else False,
    )

    if args.bounds:
        plot.show_bounds()

    if args.axes:
        plot.show_axes()

    screenshot = f"{"".join(args.fname.split(".")[:-1])}.png"
    plot.add_key_event("S", lambda: plot.screenshot(screenshot))

    plot.view_xy()
    plot.show()


if __name__ == "__main__":
    main()
